package kalkulator;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-23T23:11:39.152+02:00
 * Generated source version: 3.3.6
 *
 */
@WebService(targetNamespace = "http://www.example.org/Kalkulator/", name = "Kalkulator")
@XmlSeeAlso({ObjectFactory.class})
public interface Kalkulator {

    @WebMethod(action = "http://www.example.org/Kalkulator/sub")
    @RequestWrapper(localName = "sub", targetNamespace = "http://www.example.org/Kalkulator/", className = "kalkulator.Sub")
    @ResponseWrapper(localName = "subResponse", targetNamespace = "http://www.example.org/Kalkulator/", className = "kalkulator.SubResponse")
    @WebResult(name = "result", targetNamespace = "")
    public int sub(

        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebMethod(action = "http://www.example.org/Kalkulator/add")
    @RequestWrapper(localName = "add", targetNamespace = "http://www.example.org/Kalkulator/", className = "kalkulator.Add")
    @ResponseWrapper(localName = "addResponse", targetNamespace = "http://www.example.org/Kalkulator/", className = "kalkulator.AddResponse")
    @WebResult(name = "result", targetNamespace = "")
    public int add(

        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebMethod(action = "http://www.example.org/Kalkulator/div")
    @RequestWrapper(localName = "div", targetNamespace = "http://www.example.org/Kalkulator/", className = "kalkulator.Div")
    @ResponseWrapper(localName = "divResponse", targetNamespace = "http://www.example.org/Kalkulator/", className = "kalkulator.DivResponse")
    public void div(

        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2,
        @WebParam(mode = WebParam.Mode.OUT, name = "quotient", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> quotient,
        @WebParam(mode = WebParam.Mode.OUT, name = "rest", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.Integer> rest
    );

    @WebMethod(action = "http://www.example.org/Kalkulator/avg")
    @RequestWrapper(localName = "avg", targetNamespace = "http://www.example.org/Kalkulator/", className = "kalkulator.Avg")
    @ResponseWrapper(localName = "avgResponse", targetNamespace = "http://www.example.org/Kalkulator/", className = "kalkulator.AvgResponse")
    @WebResult(name = "result", targetNamespace = "")
    public float avg(

        @WebParam(name = "arg", targetNamespace = "")
        java.util.List<java.lang.Integer> arg
    );

    @WebMethod(action = "http://www.example.org/Kalkulator/mul")
    @RequestWrapper(localName = "mul", targetNamespace = "http://www.example.org/Kalkulator/", className = "kalkulator.Mul")
    @ResponseWrapper(localName = "mulResponse", targetNamespace = "http://www.example.org/Kalkulator/", className = "kalkulator.MulResponse")
    @WebResult(name = "result", targetNamespace = "")
    public int mul(

        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2
    );

    @WebMethod(action = "http://www.example.org/Kalkulator/inc")
    @RequestWrapper(localName = "inc", targetNamespace = "http://www.example.org/Kalkulator/", className = "kalkulator.Inc")
    @ResponseWrapper(localName = "incResponse", targetNamespace = "http://www.example.org/Kalkulator/", className = "kalkulator.IncResponse")
    @WebResult(name = "result", targetNamespace = "")
    public int inc(

        @WebParam(name = "arg", targetNamespace = "")
        int arg
    );
}
