package kalkulator;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.6
 * 2020-06-23T10:03:43.527+02:00
 * Generated source version: 3.3.6
 *
 */
@WebServiceClient(name = "KalkulatorRPC",
                  wsdlLocation = "file:/home/patryk/eclipse-kursy/20200622-JWS_Energa/PC03-KalkulatorRPC/KalkulatorRPC.wsdl",
                  targetNamespace = "http://www.example.org/KalkulatorRPC/")
public class KalkulatorRPC_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.example.org/KalkulatorRPC/", "KalkulatorRPC");
    public final static QName KalkulatorRPCSOAP = new QName("http://www.example.org/KalkulatorRPC/", "KalkulatorRPCSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/home/patryk/eclipse-kursy/20200622-JWS_Energa/PC03-KalkulatorRPC/KalkulatorRPC.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(KalkulatorRPC_Service.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/home/patryk/eclipse-kursy/20200622-JWS_Energa/PC03-KalkulatorRPC/KalkulatorRPC.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public KalkulatorRPC_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public KalkulatorRPC_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public KalkulatorRPC_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public KalkulatorRPC_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public KalkulatorRPC_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public KalkulatorRPC_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns KalkulatorRPC
     */
    @WebEndpoint(name = "KalkulatorRPCSOAP")
    public KalkulatorRPC getKalkulatorRPCSOAP() {
        return super.getPort(KalkulatorRPCSOAP, KalkulatorRPC.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns KalkulatorRPC
     */
    @WebEndpoint(name = "KalkulatorRPCSOAP")
    public KalkulatorRPC getKalkulatorRPCSOAP(WebServiceFeature... features) {
        return super.getPort(KalkulatorRPCSOAP, KalkulatorRPC.class, features);
    }

}
