package waluty.wygenerowane;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import waluty.model.*;
import waluty.pobieranie.BrakDanych;


/**
 * This class was generated by Apache CXF 3.3.10
 * 2021-08-10T16:08:12.964+02:00
 * Generated source version: 3.3.10
 *
 */
@WebService(targetNamespace = "http://vavatech.pl/waluty", name = "Waluty")
@XmlSeeAlso({ObjectFactory.class})
public interface Waluty {

    @WebMethod(action = "urn:pobierzBiezaceKursy")
    @RequestWrapper(localName = "pobierzBiezaceKursy", targetNamespace = "http://vavatech.pl/waluty", className = "waluty.wygenerowane.PobierzBiezaceKursy")
    @ResponseWrapper(localName = "pobierzBiezaceKursyResponse", targetNamespace = "http://vavatech.pl/waluty", className = "waluty.wygenerowane.PobierzBiezaceKursyResponse")
    @WebResult(name = "ExchangeRatesTable", targetNamespace = "")
    public ExchangeRatesTable pobierzBiezaceKursy() throws BrakDanych
;

    @WebMethod(action = "urn:pobierzTabeleDlaDaty")
    @RequestWrapper(localName = "pobierzTabeleDlaDaty", targetNamespace = "http://vavatech.pl/waluty", className = "waluty.wygenerowane.PobierzTabeleDlaDaty")
    @ResponseWrapper(localName = "pobierzTabeleDlaDatyResponse", targetNamespace = "http://vavatech.pl/waluty", className = "waluty.wygenerowane.PobierzTabeleDlaDatyResponse")
    @WebResult(name = "ExchangeRatesTable", targetNamespace = "")
    public ExchangeRatesTable pobierzTabeleDlaDaty(

        @WebParam(name = "data", targetNamespace = "")
        String data
    ) throws BrakDanych;

    @WebMethod(action = "urn:pobierzPrzedzial")
    @RequestWrapper(localName = "pobierzPrzedzial", targetNamespace = "http://vavatech.pl/waluty", className = "waluty.wygenerowane.PobierzPrzedzial")
    @ResponseWrapper(localName = "pobierzPrzedzialResponse", targetNamespace = "http://vavatech.pl/waluty", className = "waluty.wygenerowane.PobierzPrzedzialResponse")
    @WebResult(name = "ArrayOfExchangeRatesTable", targetNamespace = "")
    public ArrayOfExchangeRatesTable pobierzPrzedzial(

        @WebParam(name = "poczatek", targetNamespace = "")
        String poczatek,
        @WebParam(name = "koniec", targetNamespace = "")
        String koniec,
        @WebParam(name = "tabela", targetNamespace = "")
        String tabela
    ) throws BrakDanych;
}
